export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";

const MOCK_REPORTS = [
  {
    id: "r1",
    type: "company",
    companyName: "Meridian Import Co.",
    riskScore: 82,
    riskLevel: "Low",
    status: "Low Risk",
    createdAt: "2026-04-18T10:22:00Z",
  },
  {
    id: "r2",
    type: "company",
    companyName: "Apex Trade LLC",
    riskScore: 61,
    riskLevel: "Medium",
    status: "Medium Risk",
    createdAt: "2026-04-16T14:05:00Z",
  },
  {
    id: "r3",
    type: "document",
    fileName: "invoice_Q1_2026.pdf",
    status: "Valid",
    riskScore: 91,
    riskLevel: "Low",
    createdAt: "2026-04-14T08:47:00Z",
  },
  {
    id: "r4",
    type: "document",
    fileName: "contract_draft.pdf",
    status: "Anomaly Detected",
    riskScore: 34,
    riskLevel: "High",
    createdAt: "2026-04-12T16:30:00Z",
  },
  {
    id: "r5",
    type: "company",
    companyName: "Globex Trading Ltd",
    riskScore: 45,
    riskLevel: "High",
    status: "High Risk",
    createdAt: "2026-04-10T11:00:00Z",
  },
];

export async function GET(req: NextRequest) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { searchParams } = new URL(req.url);
  const id = searchParams.get("id");

  if (id) {
    const report = MOCK_REPORTS.find((r) => r.id === id);
    if (!report) return NextResponse.json({ error: "Report not found" }, { status: 404 });
    return NextResponse.json(report);
  }

  return NextResponse.json({
    reports: MOCK_REPORTS,
    total: MOCK_REPORTS.length,
    disclaimer: "All reports are generated by TradeSecurix analytics. For informational purposes only.",
  });
}
